using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dados;

/**
*   CREATE TABLE public.musica (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	titulo text NOT NULL,
	autor text NOT NULL
);

*/


[Table("musica", Schema = "public")]
public class Musica
{
    [Key]
    public int id { get; set; }

    [Required(ErrorMessage = "Os campos Título e Autor são obrigatórios!")]
    public string? titulo { get; set; }
    public string? autor {get; set; }

    public override string ToString()
    {
        return "Id = " + id + " ;; titulo = " + titulo + " ;; autor = " + autor;
    }
}